<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sonata.admin.route_loader' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\config\\Loader\\LoaderInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\config\\Loader\\Loader.php';
include_once $this->targetDirs[3].'\\vendor\\sonata-project\\admin-bundle\\src\\Route\\AdminPoolLoader.php';

return $this->services['sonata.admin.route_loader'] = new \Sonata\AdminBundle\Route\AdminPoolLoader(($this->services['sonata.admin.pool'] ?? $this->getSonata_Admin_PoolService()), array(0 => 'admin.obsluga', 1 => 'admin.osoba', 2 => 'admin.pozycja_zamowienia', 3 => 'admin.pracownik', 4 => 'admin.produkt', 5 => 'admin.rachunek', 6 => 'admin.rezerwacja', 7 => 'admin.rola', 8 => 'admin.pozycja_menu', 9 => 'admin.kategoria', 10 => 'admin.sektor', 11 => 'admin.staly_klient', 12 => 'admin.stolik', 13 => 'admin.vat'), $this);
