<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerD6UVafd\srcProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerD6UVafd/srcProdProjectContainer.php') {
    touch(__DIR__.'/ContainerD6UVafd.legacy');

    return;
}

if (!\class_exists(srcProdProjectContainer::class, false)) {
    \class_alias(\ContainerD6UVafd\srcProdProjectContainer::class, srcProdProjectContainer::class, false);
}

return new \ContainerD6UVafd\srcProdProjectContainer(array(
    'container.build_hash' => 'D6UVafd',
    'container.build_id' => 'a477f34f',
    'container.build_time' => 1526579838,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerD6UVafd');
