<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sonata.admin.route_loader' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\config\\Loader\\LoaderInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\config\\Loader\\Loader.php';
include_once $this->targetDirs[3].'\\vendor\\sonata-project\\admin-bundle\\src\\Route\\AdminPoolLoader.php';

return $this->services['sonata.admin.route_loader'] = new \Sonata\AdminBundle\Route\AdminPoolLoader(($this->services['sonata.admin.pool'] ?? $this->getSonata_Admin_PoolService()), array(0 => 'admin.blokada', 1 => 'admin.kategoria', 2 => 'admin.obsluga', 3 => 'admin.osoba', 4 => 'admin.pozycja_zamowienia', 5 => 'admin.pracownik', 6 => 'admin.produkt', 7 => 'admin.rachunek', 8 => 'admin.rezerwacja', 9 => 'admin.rola', 10 => 'admin.pozycja_menu', 11 => 'admin.sektor', 12 => 'admin.staly_klient', 13 => 'admin.stolik', 14 => 'admin.vat'), $this);
