<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIpxPjQQ\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIpxPjQQ/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerIpxPjQQ.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerIpxPjQQ\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerIpxPjQQ\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'IpxPjQQ',
    'container.build_id' => 'cabbf905',
    'container.build_time' => 1528906126,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerIpxPjQQ');
