<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container45osPVp\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container45osPVp/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container45osPVp.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container45osPVp\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container45osPVp\srcDevDebugProjectContainer(array(
    'container.build_hash' => '45osPVp',
    'container.build_id' => 'c98dcf1b',
    'container.build_time' => 1528998997,
), __DIR__.\DIRECTORY_SEPARATOR.'Container45osPVp');
